//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuietOffliner.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HttpHeaders {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HttpHeaders() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuietOffliner.Core.Resources.HttpHeaders", typeof(HttpHeaders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/html,application/xhtml+xml,application/xml,text/*;q=0.9,*/*;q=0.7.
        /// </summary>
        public static string AcceptDocs {
            get {
                return ResourceManager.GetString("AcceptDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gzip, deflate, br.
        /// </summary>
        public static string AcceptEncoding {
            get {
                return ResourceManager.GetString("AcceptEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8.
        /// </summary>
        public static string AcceptImage {
            get {
                return ResourceManager.GetString("AcceptImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-GB,en-US;q=0.9,en;q=0.8,ko;q=0.7.
        /// </summary>
        public static string AcceptLanguage {
            get {
                return ResourceManager.GetString("AcceptLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; Not;A Brand&quot;;v=&quot;99&quot;, &quot;Google Chrome&quot;;v=&quot;91&quot;, &quot;Chromium&quot;;v=&quot;91&quot;.
        /// </summary>
        public static string SecChUa {
            get {
                return ResourceManager.GetString("SecChUa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?0.
        /// </summary>
        public static string SecChUaMobile {
            get {
                return ResourceManager.GetString("SecChUaMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string SecFetchDestDocs {
            get {
                return ResourceManager.GetString("SecFetchDestDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string SecFetchDestImage {
            get {
                return ResourceManager.GetString("SecFetchDestImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to navigate.
        /// </summary>
        public static string SecFetchModeNav {
            get {
                return ResourceManager.GetString("SecFetchModeNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no-cors.
        /// </summary>
        public static string SecFetchModeNoCors {
            get {
                return ResourceManager.GetString("SecFetchModeNoCors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cross-site.
        /// </summary>
        public static string SecFetchSiteCross {
            get {
                return ResourceManager.GetString("SecFetchSiteCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to same-site.
        /// </summary>
        public static string SecFetchSiteSame {
            get {
                return ResourceManager.GetString("SecFetchSiteSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to same-origin.
        /// </summary>
        public static string SecFetchSiteSameOrigin {
            get {
                return ResourceManager.GetString("SecFetchSiteSameOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?1.
        /// </summary>
        public static string SecFetchUser {
            get {
                return ResourceManager.GetString("SecFetchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string UpgradeInsecureRequests {
            get {
                return ResourceManager.GetString("UpgradeInsecureRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4442.4 Safari/537.36.
        /// </summary>
        public static string UserAgent {
            get {
                return ResourceManager.GetString("UserAgent", resourceCulture);
            }
        }
    }
}
